library(hash)
mature_BSA_sequence <- 
"DTHKSEIAHRFKDLGEEHFKGLVLIAFSQYLQQCPFDEHVKLVNELTEFAKTCVADESHA
GCEKSLHTLFGDELCKVASLRETYGDMADCCEKQEPERNECFLSHKDDSPDLPKLKPDPN
TLCDEFKADEKKFWGKYLYEIARRHPYFYAPELLYYANKYNGVFQECCQAEDKGACLLPK
IETMREKVLASSARQRLRCASIQKFGERALKAWSVARLSQKFPKAEFVEVTKLVTDLTKV
HKECCHGDLLECADDRADLAKYICDNQDTISSKLKECCDKPLLEKSHCIAEVEKDAIPEN
LPPLTADFAEDKDVCKNYQEAKDAFLGSFLYEYSRRHPEYAVSVLLRLAKEYEATLEECC
AKDDPHACYSTVFDKLKHLVDEPQNLIKQNCDQFEKLGEYGFQNALIVRYTRKVPQVSTP
TLVEVSRSLGKVGTRCCTKPESERMPCTEDYLSLILNRLCVLHEKTPVSEKVTKCCTESL
VNRRPCFSALTPDETYVPKAFDEKLFTFHADICTLPDTEKQIKKQTALVELLKHKPKATE
EQLKTVMENFVAFVDKCCAADDKEACFAVEGPKLVVSTQTALA"

BSA_counter <- hash()

for (i in 1:nchar(mature_BSA_sequence)) {
  temp <- substr(mature_BSA_sequence, i, i)
  if (is.numeric(BSA_counter[[temp]])) {
    BSA_counter[[temp]] = BSA_counter[[temp]] + 1
  } else {
    BSA_counter[[temp]] = 1
  }
}

BSA_counter
